### ISSUE TITLE
Unable to import any image

### ISSUE THREAD

**Issue by ElVallon** [guillaumechereau/goxel#372] opened 2024-05-15 14:45 UTC
When i try to open any image, even if the area is bigger in all 3 directions than image total size (for example, 9999x9999x9999 area vs 834x546 image) the program simply shutdown (and won't let me save anything if i had make anything before that).

I hope this is fixed in near fute, as is something VERY important for me, as magicavoxel matrix size is still pretty limited to 256x256x256 which is VERY small for me and what i normally create, and qubicle suffers a lot with big matrices by lagging A LOT (despite my pc being very powerful).

**Comment by guillaumechereau** [comment] 2024-05-16 10:21
Sorry I don't really understand the issue.  What are the exact steps to reproduce it?

**Comment by ElVallon** [comment] 2024-05-16 14:26
The exact steps are:

- Open goxel;
- Go to File > Import > Image plane;
- Choose desired image to import;
- Goxel shuts down and if you had make anything before that, boom, everything lost due to the shutdown.

And doesn't matter if i go at image and change w, h and d sizes to dimensions bigger than image dimensions, goxel will still shutdown and close.

I wonder..is goxel really able to import images (png/jpg)?

**Comment by ElVallon** [comment] 2024-05-16 15:48
v0.14.0 on windows 10 pro.

**Comment by ElVallon** [comment] 2024-06-01 23:08
Idk if there is any confusion around this, but, when i say an image, i mean about png, jpg and so on.

Does goxel support importing those image files?

**Comment by guillaumechereau** [comment] 2024-06-02 07:29
yes, in my tests it seemed to work.  Maybe it depends on the exact size of
the image, or the format, or the size of the Goxel image, etc… does it
crash no matter what image you try to import?

**Comment by guillaumechereau** [comment] 2024-07-28 08:27
Closing for now cause I cannot reproduce this.

**Closed by guillaumechereau** 2024-07-28 08:27 UTC
