### ISSUE TITLE
Program don't started

### ISSUE THREAD

**Issue by maxtar** [guillaumechereau/goxel#278] opened 2022-05-01 19:03 UTC
When try to start in console got an error:
./goxel-0.10.8-linux: error while loading shared libraries: libglfw.so.3: cannot open shared object file: No such file or directory

**Comment by EZRAIDv2** [comment] 2022-05-04 07:00
Same

**Comment by maxtar** [comment] 2022-05-05 10:40
@EZRAIDv2 this command install from repository. Need to add them?

**Comment by jackoboDev** [comment] 2022-06-01 14:47
> When try to start in console got an error: ./goxel-0.10.8-linux: error while loading shared libraries: libglfw.so.3: cannot open shared object file: No such file or directory

True solution according to my Linux experience : 
sudo apt-get install libglfw3 : for classic use
sudo apt-get install libglfw3-dev : for development use

The command "sudo apt install goxel" will not install maybe the latest version of the program on some linux OS

**Comment by pegvin** [comment] 2022-07-17 12:05
glfw is not installed for some reason, you can install it via:

On Debian & it's children:
```bash
sudo apt-get install libglfw3
```

On Arch & it's children:
```
yay -S glfw3
```

**Comment by guillaumechereau** [comment] 2023-03-11 07:52
Closing because I think the issue is not in goxel itself.

**Closed by guillaumechereau** 2023-03-11 07:52 UTC
