### ISSUE TITLE
Compiling on Windows outputs en error. "unknown encoding: mbcs"

### ISSUE THREAD

**Issue by TheSlider2** [guillaumechereau/goxel#267] opened 2022-01-20 15:00 UTC
I followed the instructions to install the dependencies then ran the make command (Windows 10).
`

$ make release
scons mode=release
scons: Reading SConscript files ...
LookupError: unknown encoding: mbcs:
  File "/h/dev/VS/goxel/goxel/SConstruct", line 34:
    env = Environment(variables = vars, ENV = os.environ)
  File "/usr/lib/python3.9/site-packages/SCons/Environment.py", line 990:
    apply_tools(self, tools, toolpath)
  File "/usr/lib/python3.9/site-packages/SCons/Environment.py", line 102:
    env.Tool(tool)
  File "/usr/lib/python3.9/site-packages/SCons/Environment.py", line 1810:
    tool(self)
  File "/usr/lib/python3.9/site-packages/SCons/Tool/__init__.py", line 303:
    self.generate(env, *args, **kw)
  File "/usr/lib/python3.9/site-packages/SCons/Tool/default.py", line 40:
    for t in SCons.Tool.tool_list(env['PLATFORM'], env):
  File "/usr/lib/python3.9/site-packages/SCons/Tool/__init__.py", line 1279:
    c_compiler = FindTool(c_compilers, env) or c_compilers[0]
  File "/usr/lib/python3.9/site-packages/SCons/Tool/__init__.py", line 1174:
    if t.exists(env):
  File "/usr/lib/python3.9/site-packages/SCons/Tool/msvc.py", line 303:
    return msvc_exists(env)
  File "/usr/lib/python3.9/site-packages/SCons/Tool/MSCommon/vc.py", line 836:
    vcs = cached_get_installed_vcs(env)
  File "/usr/lib/python3.9/site-packages/SCons/Tool/MSCommon/vc.py", line 561:
    ret = get_installed_vcs(env)
  File "/usr/lib/python3.9/site-packages/SCons/Tool/MSCommon/vc.py", line 572:
    VC_DIR = find_vc_pdir(ver)
  File "/usr/lib/python3.9/site-packages/SCons/Tool/MSCommon/vc.py", line 374:
    comps = find_vc_pdir_vswhere(msvc_version)
  File "/usr/lib/python3.9/site-packages/SCons/Tool/MSCommon/vc.py", line 331:
    vsdir = vsdir.decode("mbcs").splitlines()
make: *** [Makefile:8: release] Error 2

`

**Comment by jacobpennington821** [comment] 2023-02-19 13:32
I also encountered this problem but it seemed to be because I was running the prompt in msys2.exe instead of mingw64.exe

**Comment by pegvin** [comment] 2023-02-19 15:16
kinda scons error https://github.com/msys2/MSYS2-packages/issues/2275

**Comment by guillaumechereau** [comment] 2023-03-11 08:05
Closing because the issue is not from goxel itself.

**Closed** 2023-03-11 08:05 UTC
