### ISSUE TITLE
Goxel crashes when saving if there's a selection

### ISSUE THREAD

**Issue by lancilloty** [guillaumechereau/goxel#291] opened 2022-08-25 02:25 UTC
When the selection tool is active and some blocks are selected, if I attempt to save the file goxel crashes every single time without fault. Fun part tho: it still saves the progress correctly, so that's nice, except for having to restart. This issue might be related to https://github.com/guillaumechereau/goxel/issues/211 but since it's very specific it might differ.

Goxel version: 0.10.8
OS: Latest ubuntu, all updates.

Side note: goxel is actually fun to use.

**Comment by guillaumechereau** [comment] 2022-08-25 03:38
Thanks for the report.  I'll have a look at this.

**Comment by lancilloty** [comment] 2022-08-25 04:12
Also, this was specifically for a VXL file, might be important I don't know. @guillaumechereau

**Comment by guillaumechereau** [comment] 2022-08-25 07:15
You mean it only crashes when you try to export as VXL?  If so do you have an example of faulty model I could look at?

**Comment by lancilloty** [comment] 2022-11-22 03:36
@guillaumechereau I mean I only tested it with a VXL export, not another format.

**Comment by guillaumechereau** [comment] 2023-03-11 07:56
Yes I think!  I will close this for now because I cannot reproduce the bug.  Feel free to reopen if needed.

**Closed by guillaumechereau** 2023-03-11 07:56 UTC
Labels: bug, important

**Comment by OneArb** [comment] 2023-04-25 13:07
I can reproduce the issue on 0.11.0 - Arch Linux

with a selection

      saving using menu (mouse) works
      saving using shortcut
      
 (goxel:1786178): Gtk-WARNING **: 14:39:17.531: Theme parsing error: gtk.css:9672:21: Not using units is deprecated. Assuming 'px'.
0.000: Save to /home/arch/Documents/voxel/goxel/catatonia debug/catatonia03.gox save_to_file (src/formats/gox.c:259)
0.033: Saved /home/arch/Documents/voxel/goxel/catatonia debug/catatonia03.gox sys_on_saved (src/system.c:295)
Segmentation fault (core dumped)

"Not using units is deprecated. Assuming 'px'" can be seen when saving, but not if just using goxel exiting with saving.

Also Crtl Z shortcut is not working. Undoing through the menu works.
