### ISSUE TITLE
[PROPOSAL] Add cube sizes 

### ISSUE THREAD

**Issue by dpnnl** [guillaumechereau/goxel#329] opened 2023-11-26 17:00 UTC
I would like to be able to create cubes in different sizes besides the default. In specific cubes like 0.1, 0.5 size.

**Comment by guillaumechereau** [comment] 2023-12-26 15:18
If I understand what you are asking, you can already set the size in the brush option "size".

**Comment by guillaumechereau** [comment] 2024-01-05 15:34
Closing because the issue is not very clear to me.

**Closed by guillaumechereau** 2024-01-05 15:34 UTC
