### ISSUE TITLE
Input is extremely fast.

### ISSUE THREAD

**Issue by faldor20** [guillaumechereau/goxel#56] opened 2017-08-03 10:37 UTC
All input has effect exceedingly quickly, just a half second tap of the left arrow will move the pointer in the code box about 20-30 characters worth of code left. the same happens when rotating the view with key presses or trying to change the the values in boxes by clicking buttons on either side, a half second will change most from negative 1 to positive 1.
i am running windows 10
AMD fx8320, overclocked if that matters.
radeon r9 280x
asrock fatal1ty 990fx motherboard

**Comment by faldor20** [comment] 2017-08-10 23:27
i have experienced a similar issue on my laptop, but not as extreme

**Comment by faldor20** [comment] 2017-08-16 10:07
this seems better in 0.7.1

**Comment by guillaumechereau** [comment] 2017-08-19 17:18
OK that's strange, I didn't do anything about that...

**Comment by guillaumechereau** [comment] 2023-04-09 07:55
Closing for now since I cannot reproduce it.

**Closed by guillaumechereau** 2023-04-09 07:55 UTC
Labels: bug
