### ISSUE TITLE
Enables sse flags by default -> break aarch64

### ISSUE THREAD

**Issue by Mic92** [guillaumechereau/goxel#125] opened 2018-10-03 20:29 UTC
Also it seems to hide sse specific code behind feature flags goxel seems to pass `-msse2` by default.
This breaks the build on arm8 at the moment. In case upstream cares of support on this upstream it might be a good idea to not unconditionally include this.
Recognized while reviewing `0.8.0 -> 0.8.1` update: https://github.com/NixOS/nixpkgs/pull/47789#issuecomment-426743443

**Comment by guillaumechereau** [comment] 2019-04-19 08:53
Should be fixed by now.  Please reopen if the issue is still there.

**Closed by guillaumechereau** 2019-04-19 08:53 UTC

**Comment by Mic92** [comment] 2019-04-19 10:17
Is the fix in a released version?

**Comment by guillaumechereau** [comment] 2019-04-19 10:20
Yes, the release 0.8.3 should work.  I totally removed all the cycles code that required the sse2 flags.
